name: Build & Push
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Tag-Version to upload the image"
        required: true

jobs:
  build-push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout code
        uses: actions/checkout@v2

      # Set Docker image tag
      - name: Docker image tag version (on main branch push) to file
        if: github.ref == 'refs/heads/main'
        run: "echo latest > /tmp/docker_tag_version.txt"
      - name: Docker image tag version (on develop branch push) to file
        if: github.ref == 'refs/heads/develop'
        run: "echo dev > /tmp/docker_tag_version.txt"
      - name: Docker image tag version (on workflow dispatch) to file
        if: github.event.inputs.tag_version
        run: "echo ${{ github.event.inputs.tag_version }} > /tmp/docker_tag_version.txt"
      - name: Read extracted image tag version from file
        id: get_docker_tag_version_from_file
        uses: juliangruber/read-file-action@v1
        with:
          path: "/tmp/docker_tag_version.txt"
      - name: Set image tag version to variable
        id: get_image_tag_version
        run: echo ::set-output name=VERSION::$(echo ${{ steps.get_docker_tag_version_from_file.outputs.content }})
      - name: Validate image tag version
        id: validate_image_tag_version
        run: "test ${{ steps.get_image_tag_version.outputs.VERSION }} || exit 1"

      # Setup building dependencies
      - name: Install QEMU
        uses: docker/setup-qemu-action@v1
        if: success()
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: success()

      # Docker login
      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build & Push
      - name: Build & Push for all archs
        if: success()
        run: make buildx IMAGE_TAG=davidlor/ssh-port-forward-server:${{ steps.get_image_tag_version.outputs.VERSION }} ARCH=linux/amd64,linux/arm/v7
